/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package lu.pistache.avro.kafka;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum StatusEnum { 
  ALIVE, KICKING, DEAD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"StatusEnum\",\"namespace\":\"lu.pistache.avro\",\"symbols\":[\"ALIVE\",\"KICKING\",\"DEAD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
