/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package lu.pistache.avro.kafka;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface UserInterface {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"UserInterface\",\"namespace\":\"lu.pistache.avro\",\"types\":[{\"type\":\"enum\",\"name\":\"StatusEnum\",\"symbols\":[\"ALIVE\",\"KICKING\",\"DEAD\"]},{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"addressId\",\"type\":\"int\"},{\"name\":\"Line1\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"Line2\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"Line3\",\"type\":[\"null\",\"string\"],\"default\":null}]},{\"type\":\"record\",\"name\":\"User\",\"fields\":[{\"name\":\"Id\",\"type\":\"long\"},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"Surname\",\"type\":\"string\",\"default\":\"Doe\"},{\"name\":\"Status\",\"type\":[\"null\",\"StatusEnum\"],\"default\":null},{\"name\":\"Address\",\"type\":[\"null\",\"Address\"],\"default\":null},{\"name\":\"AlternativeAddress\",\"type\":[\"null\",\"Address\"],\"default\":null}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends UserInterface {
    public static final org.apache.avro.Protocol PROTOCOL = UserInterface.PROTOCOL;
  }
}